#define DIALOGWIN                   100
#define EF_A1                       102
#define EF_A2                       103
#define EF_A3                       104
#define EF_A4                       105
#define SBH                         106
#define LT_NET                      107
#define TXT_MB                      120
#define TXT_M                       121
#define TXT_SB                      122
#define TXT_HB                      123
#define TXT_NS                      124
#define TXT_NH                      125
#define TXT_T                       126
#define TXT_CN                      127
#define TXT_CHR                     128
#define TXT_CB                      129
#define PB_CALCULATE                130
#define PB_ABOUT                    131
#define PB_EXIT                     132
